### PR TITLE
Team 3, solve euler equation to get b2

### PR DESCRIPTION
**Pull request by Alexander-Weinberg**
In the euler.py script, our first function defines the euler equation error and our second function solves for the amount of savings that optimizes euler equation.

### CODE REVIEW

**Comment by rickecon** [comment]
Get rid of those changes to the `README.md`, get rid or the two `.DS_Store` files. @evanjflack will submit a PR that fixes the `.gitignore`.

**Comment by rickecon** [comment]
@Alexander-Weinberg The `args` tuple elements are not unpacked inside each function. Did you guys test this? And I would like you to get rid of extra spaces between the function docstrings and the executing code in the functions.

**Comment by Alexander-Weinberg** [comment]
@rickecon Should be all fixed. Deleted the DS and edited readme

**Comment by rickecon** [comment]
@Alexander-Weinberg asked to close this.

**Pull request closed without merging**
