### PR TITLE
Created FirmMC equations

### PR DESCRIPTION
**Pull request by nadavtadelis**

### CODE REVIEW

**Comment by ghost** [comment]
Looks awesome!

**Comment by nadavtadelis** [comment]
@OI-nthor @paulineliang7829 @gen-li @jettpettus @nicolas-jimenez @evanjflack

**Comment by glesnick** [comment]
This is a good pull request but it seems fishy that there were no issues.

**Comment by rickecon** [comment]
@nadavtadelis Just change a couple of things, and then I think we're good. All the functions look right, and I like the `.gitignore` changes.
* Only put one space between the end of the executing code in the functions and the `return` argument.
* Get rid of the extra line put in the `README.md`.

**Pull request merged**
